test('First test', () => {

});

test('Second test', () => {
  throw new Error("Something failed.");
});